### ISSUE TITLE
Test cameras

### ISSUE THREAD

**Issue by Partins** [kottz/D7039E#15]
- [ ] See if cameras work with the NVIDIA
- [ ] Establish a pipeline from cameras to OpenCV
- [ ] Write all the steps in the wiki

**Comment by Partins** [comment]
How is this going? Please add it to a milestone

**Comment by kottz** [comment]
This issue can be closed. The cameras are accessed through GStreamer which in turn can be used as an input in OpenCV.

This repository contains some examples: https://github.com/JetsonHacksNano/CSI-Camera.

Our configuration can be seen in the MV source code.
