### ISSUE TITLE
3D-print a box for the NVIDIA

### ISSUE THREAD

**Issue by Partins** [kottz/D7039E#16]
Design or 3D-print a box for the NVIDIA. 

Also att a power button and Power LED

**Comment by Partins** [comment]
This will be good for now: https://www.thingiverse.com/thing:3603594

**Comment by NiklasDahlquist1** [comment]
The 3d model has been printed

**Comment by Partins** [comment]
We'll assemble it when Edward K returns with the NVIDIA, then we'll close this issue

**Comment by Partins** [comment]
Done and assembled. No power button or LED for now. Closing...
