### ISSUE TITLE
Make the base move

### ISSUE THREAD

**Issue by Partins** [kottz/D7039E#26]
Stuff to be done

- [x] Print motor-wheel adapters 2x
- [x] Print base-motors adapters  2x
- [x] Assemble the tracks with motors
- [x] Mount tracks to base
- [x] Connect motors to RPi
- [x] Set motors in wheel mode
- [x] Write a simple program to move it

**Comment by Partins** [comment]
There were some problems. We're waiting for the USB2Dynamixeladapter.

**Comment by Partins** [comment]
@mnsnor please close this

**Comment by mnsnor** [comment]
We have been able to hardcode the motors to move and turn
