### ISSUE TITLE
Get line coordinates

### ISSUE THREAD

**Issue by Partins** [kottz/D7039E#4]
Get some kind of coordinates for the tracked line

**Comment by kottz** [comment]
First prototype of line tracker is done.

**Todo:**
- Establish an API
- ROS port (C++ maybe?)
- Clean up code and add configuration capabilities
- Add QR code reader.

**Comment by kottz** [comment]
Tried running the prototype python implementation on my rpi4. Performance wasn't great so will definitely port the system to C++.

**Comment by Partins** [comment]
NVIDIA is ready to be worked on if you need to borrow it. Just tell the other group if you intend on using it next week

**Comment by kottz** [comment]
Closing this issue since basic functionality is implemented. Future optimizations will be created new issues.
