### ISSUE TITLE
CAD Model of arm V1

### ISSUE THREAD

**Issue by Partins** [kottz/D7039E#6]
Have an initial version ready for evaluation

**Comment by NiklasDahlquist1** [comment]
Plastic links between the servos were suplied with the servos, and a base mount plate has been 3d printed. 

A longer arm might be needed later, but this will be used for now,

![robot arm](https://user-images.githubusercontent.com/58167510/94603622-ca75cd80-0296-11eb-966f-831cfb412a0d.jpg)
